### ISSUE TITLE
EasyOgreExporter.dle for 2020 is still v3.2.1, even in the EOE installer

### ISSUE THREAD

**Issue by bdotq** [OGRECave/EasyOgreExporter#3]
EasyOgreExporter.dle for max 2020 is still v3.2.1, even in the EOE installer. Trying to see if materials will export properly to v2.
Having a HELL of a time trying to get EOE 3.2.2 to build ... so far only days of frustration.

**Comment by paroj** [comment]
should be fixed with 25155884884f92ff4e81366c6d3adc12a46faaba
